apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-c-1
    image: nginx123       # intentionally wrong image name
    ports:
    - containerPort: 80

